/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_car_rental;

import Classes.Car;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ydnek
 */
public class Form_CarImages extends javax.swing.JFrame {

    /**
     * Creates new form Form_CarImages
     */
    
          Car car = new Car();
          ArrayList<Car> carList = car.carsList(); 
         ArrayList<Car.CarImage> carImages; 
          
          
    public Form_CarImages() {
        initComponents();

        this.setLocationRelativeTo(null);
        
         populateJtableWithCar();
                 }
    
    // function to  resize the imge so it can fit the jlabel
         public void displayimages(int width, int height,String image_path,JLabel label)
    {
        // get the images 
        ImageIcon imageIcon = new ImageIcon(image_path);
        // resize the image
        Image image = imageIcon.getImage().getScaledInstance(width, height,  Image.SCALE_SMOOTH);
        // set the image into the jlabel
        label.setIcon(new ImageIcon(image));
    }
         
            public void displayByteImage(int width, int height,byte[] image_byte,JLabel label)
    {
        // get the images
        
        ImageIcon imageIcon = new ImageIcon(image_byte);
        // resize the image
        Image image = imageIcon.getImage().getScaledInstance(width, height,  Image.SCALE_SMOOTH);
        // set the image into the jlabel
        label.setIcon(new ImageIcon(image));
    }   
         
                     // create a function to  select an image
            // the function will return the image path 
    public String selectImage(){
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select Picture");
        
        fileChooser.setCurrentDirectory(new File("C:\\Users\\fanos\\OneDrive\\Pictures\\CARS"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("image","png","jpg");
        fileChooser.addChoosableFileFilter(filter);
        
        int state = fileChooser.showSaveDialog(null);
        String path = "";
        
        if(state== JFileChooser.APPROVE_OPTION){
            path = fileChooser.getSelectedFile().getAbsolutePath();
        }
        
        return path;
    }
    
           // create a function to populate the Table 
        public void populateJtableWithCar(){
            // Table columns
        String [] columnsName = {"Id","Model","Class"};        
        
        // jtable rows
        Object[][] rows = new Object[carList.size()] [columnsName.length];
        
        for(int i = 0;i < carList.size();i++){
            
            rows[i][0] = carList.get(i).getId();
            rows[i][1] = carList.get(i).getModel();
            rows[i][2] = carList.get(i).getCalss_();
        }
        
        DefaultTableModel model = new DefaultTableModel(rows,columnsName);
        
        Table_Car.setModel(model);  
    }
        
                   // create a function to populate the Table 
        public void populateJtableWithCarImage(int car_id)
        {
            ArrayList<Car.CarImage> ImageList = car.carImageList(car_id);
            // Table columns
            String [] columnsName = {"Image ID"};
           
             // jtable rows,
            Object[][] rows = new Object[ImageList.size()] [columnsName.length];

            for(int i = 0;i < ImageList.size();i++)
            {
                rows[i][0] = ImageList.get(i).getImg_id();
            }

            DefaultTableModel model = new DefaultTableModel(rows,columnsName);

            Table_Car_image.setModel(model);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lbl_brands_logo2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_close2 = new javax.swing.JLabel();
        jLabel_for_back2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Car = new javax.swing.JTable();
        lbl_image_path = new javax.swing.JLabel();
        jLabel_CarImage = new javax.swing.JLabel();
        jButton_selectImange = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton_removeImage = new javax.swing.JButton();
        jButtonImageslider = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_Car_image = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton_AddImange = new javax.swing.JButton();
        jLabel_imagePath = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1080, 600));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 600));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.setToolTipText("");
        jPanel6.setPreferredSize(new java.awt.Dimension(1075, 580));

        jPanel7.setBackground(new java.awt.Color(255, 102, 102));

        lbl_brands_logo2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        lbl_brands_logo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_brands_logo2.setText("brands log");

        jLabel7.setBackground(new java.awt.Color(64, 73, 220));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cars Images");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel_close2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_close2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close2.setText("x");
        jLabel_close2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_close2MouseClicked(evt);
            }
        });

        jLabel_for_back2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel_for_back2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_for_back2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_for_back2.setText("<");
        jLabel_for_back2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_for_back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_for_back2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel_for_back2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(lbl_brands_logo2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
                .addComponent(jLabel_close2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_close2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_for_back2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbl_brands_logo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );

        Table_Car.setAutoCreateRowSorter(true);
        Table_Car.setBackground(new java.awt.Color(255, 255, 255));
        Table_Car.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0)));
        Table_Car.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Table_Car.setForeground(new java.awt.Color(0, 0, 0));
        Table_Car.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Table_Car.setToolTipText("");
        Table_Car.setFocusTraversalPolicyProvider(true);
        Table_Car.setGridColor(new java.awt.Color(0, 0, 0));
        Table_Car.setInheritsPopupMenu(true);
        Table_Car.setRowHeight(40);
        Table_Car.setSelectionBackground(new java.awt.Color(102, 102, 255));
        Table_Car.setSelectionForeground(new java.awt.Color(0, 0, 0));
        Table_Car.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_CarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Car);

        lbl_image_path.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel_CarImage.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_CarImage.setForeground(new java.awt.Color(102, 102, 102));
        jLabel_CarImage.setOpaque(true);

        jButton_selectImange.setBackground(new java.awt.Color(255, 102, 102));
        jButton_selectImange.setForeground(new java.awt.Color(0, 0, 0));
        jButton_selectImange.setText("Select Image");
        jButton_selectImange.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(51, 255, 255), null, null));
        jButton_selectImange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_selectImange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_selectImangeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cars");

        jButton_removeImage.setBackground(new java.awt.Color(255, 102, 102));
        jButton_removeImage.setForeground(new java.awt.Color(0, 0, 0));
        jButton_removeImage.setText("Remove Image");
        jButton_removeImage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(51, 255, 255), null, null));
        jButton_removeImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_removeImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_removeImageActionPerformed(evt);
            }
        });

        jButtonImageslider.setBackground(new java.awt.Color(255, 102, 102));
        jButtonImageslider.setForeground(new java.awt.Color(0, 0, 0));
        jButtonImageslider.setText("Image Slider");
        jButtonImageslider.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(51, 255, 255), null, null));
        jButtonImageslider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonImageslider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImagesliderActionPerformed(evt);
            }
        });

        Table_Car_image.setAutoCreateRowSorter(true);
        Table_Car_image.setBackground(new java.awt.Color(255, 255, 255));
        Table_Car_image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0)));
        Table_Car_image.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Table_Car_image.setForeground(new java.awt.Color(0, 0, 0));
        Table_Car_image.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Table_Car_image.setToolTipText("");
        Table_Car_image.setFocusTraversalPolicyProvider(true);
        Table_Car_image.setGridColor(new java.awt.Color(0, 0, 0));
        Table_Car_image.setInheritsPopupMenu(true);
        Table_Car_image.setSelectionBackground(new java.awt.Color(102, 102, 255));
        Table_Car_image.setSelectionForeground(new java.awt.Color(0, 0, 0));
        Table_Car_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_Car_imageMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table_Car_image);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Selected Car Image");

        jButton_AddImange.setBackground(new java.awt.Color(255, 102, 102));
        jButton_AddImange.setForeground(new java.awt.Color(0, 0, 0));
        jButton_AddImange.setText("Add Image");
        jButton_AddImange.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(51, 255, 255), null, null));
        jButton_AddImange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_AddImange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddImangeActionPerformed(evt);
            }
        });

        jLabel_imagePath.setFont(new java.awt.Font("Segoe UI", 0, 5)); // NOI18N
        jLabel_imagePath.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_imagePath.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lbl_image_path, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_CarImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_selectImange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_removeImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonImageslider, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(jButton_AddImange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_imagePath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel_CarImage, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_imagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_selectImange, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_AddImange, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_removeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonImageslider, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(lbl_image_path)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1087, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_close2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_close2MouseClicked
        // TO Close the Program 
                               int confirm = JOptionPane.showConfirmDialog(null, "Are You Sure You Want to Exit", "Confirm",JOptionPane.YES_NO_OPTION);
                if(confirm==JOptionPane.YES_OPTION)
                {
                    System.exit(0);
                }
    }//GEN-LAST:event_jLabel_close2MouseClicked

    private void jLabel_for_back2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_for_back2MouseClicked
        // TODO add your handling code here:

        Form_Car dashboard = new Form_Car();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_for_back2MouseClicked

    private void Table_CarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_CarMouseClicked
        // get the selected car Model
         jLabel_CarImage.setIcon(null);
        int index = Table_Car.getSelectedRow();
        int car_id = Integer.valueOf(Table_Car.getValueAt(index,0).toString());
        //System.out.println(id);
        populateJtableWithCarImage(car_id);
        carImages =car.carImageList(car_id); 
    }//GEN-LAST:event_Table_CarMouseClicked

    private void Table_Car_imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_Car_imageMouseClicked
        // Display the Selected image
       
         int index = Table_Car_image.getSelectedRow();
        int image_id = Integer.valueOf(Table_Car_image.getValueAt(index,0).toString());
        
        byte[] img = null;
        for(Car.CarImage cimg : carImages)
        {
            if(cimg.getImg_id() == image_id)
            {
                img = cimg.getCar_img();
            }
        }
        
        displayByteImage(jLabel_CarImage.getWidth(),jLabel_CarImage.getHeight(),img,jLabel_CarImage);
    }//GEN-LAST:event_Table_Car_imageMouseClicked

    private void jButton_selectImangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_selectImangeActionPerformed
        // browse and display
        
           String imagePath = selectImage();
           displayimages(jLabel_CarImage.getWidth(),jLabel_CarImage.getHeight(),imagePath,jLabel_CarImage);
        // display the image path
           jLabel_imagePath.setText(imagePath);
        
    }//GEN-LAST:event_jButton_selectImangeActionPerformed

    private void jButton_removeImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_removeImageActionPerformed
        // Remove image
        // get image by id
        
        try
        {
            int index = Table_Car_image.getSelectedRow();
            int image_id = Integer.valueOf(Table_Car_image.getValueAt(index,0).toString());
            int confirm = JOptionPane.showConfirmDialog(null, "Are You Sure You Want to Delete this Car Image", "Confirm",JOptionPane.YES_NO_OPTION);
            if(confirm==JOptionPane.YES_OPTION)
            {
                car.removeCarImage(image_id);
            }
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Select the Image First","Delete Car Image",2);
        }
        
    }//GEN-LAST:event_jButton_removeImageActionPerformed

    private void jButton_AddImangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddImangeActionPerformed
        //  add car image
                try {
                   // get car id from the jtable
                    int  index = Table_Car.getSelectedRow();
                    int car_id = Integer.valueOf(Table_Car.getValueAt(index, 0).toString());
                    byte[]  image = Files.readAllBytes(Paths.get(jLabel_imagePath.getText()));
                    
                    car.addCarImage(car_id, image);
                    
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Select An Image [ "+ex+" ]","Invalid Info",2);
                }
    }//GEN-LAST:event_jButton_AddImangeActionPerformed

    private void jButtonImagesliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImagesliderActionPerformed
        // show image (form the selected car )  slider 
       // get the selected car image
       
        int index = Table_Car.getSelectedRow();
        int id = Integer.valueOf(Table_Car.getValueAt(index,0).toString()); // car id 
        Form_CarImages_Slider slider = new Form_CarImages_Slider(id);
        slider.setVisible(true);
        
    }//GEN-LAST:event_jButtonImagesliderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Form_CarImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Form_CarImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Form_CarImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Form_CarImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_CarImages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Car;
    private javax.swing.JTable Table_Car_image;
    private javax.swing.JButton jButtonImageslider;
    private javax.swing.JButton jButton_AddImange;
    private javax.swing.JButton jButton_removeImage;
    private javax.swing.JButton jButton_selectImange;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_CarImage;
    private javax.swing.JLabel jLabel_close2;
    private javax.swing.JLabel jLabel_for_back2;
    private javax.swing.JLabel jLabel_imagePath;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_brands_logo2;
    private javax.swing.JLabel lbl_image_path;
    // End of variables declaration//GEN-END:variables
}
