/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_car_rental;

import Classes.Booking;
import Classes.Brand_Cls;
import Classes.Car;
import Classes.Location;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Ydnek
 */
public class Form_BookCar extends javax.swing.JFrame {

    Border border = BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(51,0,153));
    Border white_border  = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
    Border empty_border  = BorderFactory.createMatteBorder(1, 1, 1, 1, new  Color( 0,204,204));
    Border panel_border  = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.darkGray);
    
    Car car = new Car();
    Booking booking = new Booking();
    Location location = new Location(); 
    Brand_Cls brand = new Brand_Cls();
    HashMap<Integer, String > map = brand.brandHasMap();    
    /**
     * Creates new form Form_BookCar
     */
    public Form_BookCar() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        populateComboboxBrands();
        // set border
        jLabel_select_a_car.setBorder(border);
        jLabel_select_customer.setBorder(border);
        jLabel_pick_up.setBorder(border);
        jLabel_drop_off.setBorder(border);
        
        jPanel_drop_off.setBorder(panel_border);
        jPanel_pick_up.setBorder(panel_border);
        jPanel_select_car.setBorder(panel_border);
        jPanel_select_customer.setBorder(panel_border);
        
    }
    
    // static function to dispaly customer id and name
    
    public static void dispalyCustomer(String id ,String name)
    {
        jTextField_customer_name.setText(name);
        jLabel_customer_id.setText(id);
    }
    
        // static function to dispaly customer id and name
    
    public static void dispalyCarInfo(String id ,String model,String price)
    {    
        jLabel_car_model.setText(model);
        jLabel_car_id.setText(id);
        jLabel_car_price.setText(price);
    }
    
    // function to populate Combobox brand
    public void populateComboboxBrands()
    { 
        for( String s : map.values())
        {
            jComboBox_brand.addItem(s);
        } 
    }
    
        // function to populate Combobox brand
    public void populateComboboxAddress(String pickup_or_dropoff , String city)
    { 
        if (pickup_or_dropoff.equals("pickup"))
        {
            // clear combobox 
            jComboBox_address.removeAllItems();
            
               for( Location l : location.locationListByCity(city))
               {
                   jComboBox_address.addItem(l.getAddress());
               } 
        }
     
        else if (pickup_or_dropoff.equals("dropoff"))
        {
            // clear combobox 
            jComboBox_address2.removeAllItems();
            
            for( Location l : location.locationListByCity(city))
            {
                jComboBox_address2.addItem(l.getAddress());
            }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_Tittle = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jLabel_for_back = new javax.swing.JLabel();
        jPanel_select_car = new javax.swing.JPanel();
        jLabel_select_a_car = new javax.swing.JLabel();
        jLabel_brand = new javax.swing.JLabel();
        jLabel_car = new javax.swing.JLabel();
        jComboBox_brand = new javax.swing.JComboBox<>();
        jLabel_brand_id = new javax.swing.JLabel();
        jLabel_customer_id1 = new javax.swing.JLabel();
        jLabel_car_id = new javax.swing.JLabel();
        jLabel_customer_id5 = new javax.swing.JLabel();
        jButton_select_car = new javax.swing.JButton();
        jLabel_car_model = new javax.swing.JLabel();
        jLabel_customer_id6 = new javax.swing.JLabel();
        jLabel_car_price = new javax.swing.JLabel();
        jLabel_customer_price1 = new javax.swing.JLabel();
        jPanel_pick_up = new javax.swing.JPanel();
        jLabel_pick_up = new javax.swing.JLabel();
        jLabel_city = new javax.swing.JLabel();
        jLabel_address = new javax.swing.JLabel();
        jLabel_date = new javax.swing.JLabel();
        jLabel_time = new javax.swing.JLabel();
        jComboBox_city = new javax.swing.JComboBox<>();
        jComboBox_address = new javax.swing.JComboBox<>();
        jDateChooser_date = new com.toedter.calendar.JDateChooser();
        timePicker_time = new com.github.lgooddatepicker.components.TimePicker();
        jPanel_select_customer = new javax.swing.JPanel();
        jLabel_select_customer = new javax.swing.JLabel();
        jLabel_customer = new javax.swing.JLabel();
        jTextField_customer_name = new javax.swing.JTextField();
        jLabel_customer_id3 = new javax.swing.JLabel();
        jLabel_customer_id = new javax.swing.JLabel();
        jButton_Select_Cusstomer = new javax.swing.JButton();
        jPanel_drop_off = new javax.swing.JPanel();
        jLabel_drop_off = new javax.swing.JLabel();
        jLabel_city2 = new javax.swing.JLabel();
        jLabel_address2 = new javax.swing.JLabel();
        jLabel_date2 = new javax.swing.JLabel();
        jLabel_time2 = new javax.swing.JLabel();
        jComboBox_city2 = new javax.swing.JComboBox<>();
        jComboBox_address2 = new javax.swing.JComboBox<>();
        jDateChooser_date2 = new com.toedter.calendar.JDateChooser();
        timePicker_time2 = new com.github.lgooddatepicker.components.TimePicker();
        jButton_BookCar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel_car_totalprice = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 600));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setToolTipText("");

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel_Tittle.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel_Tittle.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Tittle.setText("Book a Car");
        jLabel_Tittle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel_close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("x");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
        });

        jLabel_for_back.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel_for_back.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_for_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_for_back.setText("<");
        jLabel_for_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_for_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_for_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_for_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_for_backMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel_for_back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265)
                .addComponent(jLabel_Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_for_back, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 65, Short.MAX_VALUE))
            .addComponent(jLabel_Tittle, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel_select_car.setBackground(new java.awt.Color(204, 255, 255));
        jPanel_select_car.setForeground(new java.awt.Color(0, 0, 0));

        jLabel_select_a_car.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_select_a_car.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_select_a_car.setForeground(new java.awt.Color(51, 0, 153));
        jLabel_select_a_car.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_select_a_car.setText("Select A Car");

        jLabel_brand.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_brand.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_brand.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_brand.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_brand.setText("Brand:");

        jLabel_car.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_car.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_car.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_car.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_car.setText("Car:");

        jComboBox_brand.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_brand.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_brandActionPerformed(evt);
            }
        });

        jLabel_brand_id.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_brand_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_brand_id.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_brand_id.setText("000");

        jLabel_customer_id1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_customer_id1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_customer_id1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_customer_id1.setText("ID:");

        jLabel_car_id.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_car_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_car_id.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_car_id.setText("000");

        jLabel_customer_id5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_customer_id5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_customer_id5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_customer_id5.setText("ID:");

        jButton_select_car.setText("Select Car");
        jButton_select_car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_select_carActionPerformed(evt);
            }
        });

        jLabel_car_model.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_car_model.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_car_model.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_car_model.setText("000");

        jLabel_customer_id6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_customer_id6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_customer_id6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_customer_id6.setText("Model:");

        jLabel_car_price.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_car_price.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_car_price.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_car_price.setText("000");

        jLabel_customer_price1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_customer_price1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_customer_price1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_customer_price1.setText("Price:");

        javax.swing.GroupLayout jPanel_select_carLayout = new javax.swing.GroupLayout(jPanel_select_car);
        jPanel_select_car.setLayout(jPanel_select_carLayout);
        jPanel_select_carLayout.setHorizontalGroup(
            jPanel_select_carLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_select_a_car, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_select_carLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_select_carLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_select_carLayout.createSequentialGroup()
                        .addComponent(jLabel_car, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_select_car, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_select_carLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_customer_id6)
                            .addComponent(jLabel_customer_id5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_select_carLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_car_model, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_select_carLayout.createSequentialGroup()
                                .addComponent(jLabel_car_id, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_customer_price1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_car_price, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_select_carLayout.createSequentialGroup()
                        .addComponent(jLabel_brand, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_brand, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_customer_id1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_brand_id, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        jPanel_select_carLayout.setVerticalGroup(
            jPanel_select_carLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_select_carLayout.createSequentialGroup()
                .addComponent(jLabel_select_a_car, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_select_carLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_brand, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_customer_id1)
                    .addComponent(jLabel_brand_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_select_carLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_car, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_customer_id5)
                    .addComponent(jLabel_car_id)
                    .addComponent(jButton_select_car)
                    .addGroup(jPanel_select_carLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_customer_price1)
                        .addComponent(jLabel_car_price)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_select_carLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_customer_id6)
                    .addComponent(jLabel_car_model))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel_pick_up.setBackground(new java.awt.Color(204, 255, 255));
        jPanel_pick_up.setForeground(new java.awt.Color(0, 0, 0));
        jPanel_pick_up.setPreferredSize(new java.awt.Dimension(460, 200));

        jLabel_pick_up.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_pick_up.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_pick_up.setForeground(new java.awt.Color(51, 0, 153));
        jLabel_pick_up.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_pick_up.setText("Pick Up Location & Date");

        jLabel_city.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_city.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_city.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_city.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_city.setText("City:");

        jLabel_address.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_address.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_address.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_address.setText("Address:");

        jLabel_date.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_date.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_date.setText("Date:");

        jLabel_time.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_time.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_time.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_time.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_time.setText("Time:");

        jComboBox_city.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_city.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "City 1", "City 2", "City 3", "City 4" }));
        jComboBox_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_cityActionPerformed(evt);
            }
        });

        jComboBox_address.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_address.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel_pick_upLayout = new javax.swing.GroupLayout(jPanel_pick_up);
        jPanel_pick_up.setLayout(jPanel_pick_upLayout);
        jPanel_pick_upLayout.setHorizontalGroup(
            jPanel_pick_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_pick_up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_pick_upLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_pick_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_pick_upLayout.createSequentialGroup()
                        .addComponent(jLabel_city, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_city, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_pick_upLayout.createSequentialGroup()
                        .addComponent(jLabel_address, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_address, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_pick_upLayout.createSequentialGroup()
                        .addComponent(jLabel_date, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_pick_upLayout.createSequentialGroup()
                        .addComponent(jLabel_time, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(timePicker_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_pick_upLayout.setVerticalGroup(
            jPanel_pick_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_pick_upLayout.createSequentialGroup()
                .addComponent(jLabel_pick_up, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_pick_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_city, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_pick_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_address, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_pick_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_date, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_pick_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_time, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timePicker_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanel_select_customer.setBackground(new java.awt.Color(204, 255, 255));
        jPanel_select_customer.setForeground(new java.awt.Color(0, 0, 0));
        jPanel_select_customer.setPreferredSize(new java.awt.Dimension(460, 200));

        jLabel_select_customer.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_select_customer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_select_customer.setForeground(new java.awt.Color(51, 0, 153));
        jLabel_select_customer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_select_customer.setText("Select Customer");

        jLabel_customer.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_customer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_customer.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_customer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_customer.setText("Customer:");

        jTextField_customer_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel_customer_id3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_customer_id3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_customer_id3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_customer_id3.setText("ID:");

        jLabel_customer_id.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_customer_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_customer_id.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_customer_id.setText("000");

        jButton_Select_Cusstomer.setText("Select Customer");
        jButton_Select_Cusstomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Select_CusstomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_select_customerLayout = new javax.swing.GroupLayout(jPanel_select_customer);
        jPanel_select_customer.setLayout(jPanel_select_customerLayout);
        jPanel_select_customerLayout.setHorizontalGroup(
            jPanel_select_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_select_customer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_select_customerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_customer)
                .addGap(18, 18, 18)
                .addGroup(jPanel_select_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_select_customerLayout.createSequentialGroup()
                        .addComponent(jLabel_customer_id3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_customer_id, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_select_customerLayout.createSequentialGroup()
                        .addComponent(jTextField_customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Select_Cusstomer)
                        .addGap(25, 25, 25))))
        );
        jPanel_select_customerLayout.setVerticalGroup(
            jPanel_select_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_select_customerLayout.createSequentialGroup()
                .addComponent(jLabel_select_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_select_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Select_Cusstomer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_select_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_customer_id3)
                    .addComponent(jLabel_customer_id))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jPanel_drop_off.setBackground(new java.awt.Color(204, 255, 255));
        jPanel_drop_off.setForeground(new java.awt.Color(0, 0, 0));
        jPanel_drop_off.setPreferredSize(new java.awt.Dimension(445, 200));

        jLabel_drop_off.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_drop_off.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_drop_off.setForeground(new java.awt.Color(51, 0, 153));
        jLabel_drop_off.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_drop_off.setText("Drop off Location & Date");

        jLabel_city2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_city2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_city2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_city2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_city2.setText("City:");

        jLabel_address2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_address2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_address2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_address2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_address2.setText("Address:");

        jLabel_date2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_date2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_date2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_date2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_date2.setText("Date:");

        jLabel_time2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_time2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_time2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_time2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_time2.setText("Time:");

        jComboBox_city2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_city2.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_city2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "City 1", "City 2", "City 3", "City 4" }));
        jComboBox_city2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_city2ActionPerformed(evt);
            }
        });

        jComboBox_address2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_address2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel_drop_offLayout = new javax.swing.GroupLayout(jPanel_drop_off);
        jPanel_drop_off.setLayout(jPanel_drop_offLayout);
        jPanel_drop_offLayout.setHorizontalGroup(
            jPanel_drop_offLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_drop_off, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
            .addGroup(jPanel_drop_offLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_drop_offLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_drop_offLayout.createSequentialGroup()
                        .addComponent(jLabel_city2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_city2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_drop_offLayout.createSequentialGroup()
                        .addComponent(jLabel_address2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_address2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_drop_offLayout.createSequentialGroup()
                        .addComponent(jLabel_date2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser_date2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_drop_offLayout.createSequentialGroup()
                        .addComponent(jLabel_time2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(timePicker_time2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_drop_offLayout.setVerticalGroup(
            jPanel_drop_offLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_drop_offLayout.createSequentialGroup()
                .addComponent(jLabel_drop_off, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_drop_offLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_city2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_city2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_drop_offLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_address2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_address2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_drop_offLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_date2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser_date2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_drop_offLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_time2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timePicker_time2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jButton_BookCar.setText("Book This Car");
        jButton_BookCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BookCarActionPerformed(evt);
            }
        });

        jPanel4.setPreferredSize(new java.awt.Dimension(169, 30));

        jLabel_car_totalprice.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_car_totalprice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_car_totalprice.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_car_totalprice.setText("000");

        jButton1.setText("Total Price:");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel_car_totalprice, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_car_totalprice, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_BookCar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel_select_customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_select_car, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_drop_off, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_pick_up, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel_select_car, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_select_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_BookCar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel_pick_up, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel_drop_off, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_for_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_for_backMouseExited
        // TODO add your handling code here:
        jLabel_for_back.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_for_backMouseExited

    private void jLabel_for_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_for_backMouseEntered
        // TODO add your handling code here:
        jLabel_for_back.setBorder(white_border);
    }//GEN-LAST:event_jLabel_for_backMouseEntered

    private void jLabel_for_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_for_backMouseClicked
        // TODO add your handling code here:

        Form_Dashboard dashboard = new Form_Dashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_for_backMouseClicked

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        // TODO add your handling code here:
        jLabel_close.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        // TODO add your handling code here:
        jLabel_close.setBorder(white_border);
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        // close the form
        int confirm = JOptionPane.showConfirmDialog(null, "Are You Sure You Want to Exit", "Confirm",JOptionPane.YES_NO_OPTION);
        if(confirm==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jButton_Select_CusstomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Select_CusstomerActionPerformed
        // Show Customer List 
        Form_CustomersList clist =new  Form_CustomersList();
        clist.setVisible(true);
    }//GEN-LAST:event_jButton_Select_CusstomerActionPerformed

    private void jComboBox_brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_brandActionPerformed
        // TODO add your handling code here:
                int brand_id = 0;
        for(Map.Entry<Integer, String > entry : map.entrySet())
        {
            if(entry.getValue().equals(jComboBox_brand.getSelectedItem().toString()))
            {
                brand_id = entry.getKey();
            }
         }
        jLabel_brand_id.setText(String.valueOf(brand_id));
    }//GEN-LAST:event_jComboBox_brandActionPerformed

    private void jButton_select_carActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_select_carActionPerformed
      
        // get the brand id 
        int brand_id = Integer.valueOf(jLabel_brand_id.getText());
        


        // Show The Cars list form
        Form_CarListByBrand carbybrand = new Form_CarListByBrand(brand_id);
        carbybrand.setVisible(true);
        
    }//GEN-LAST:event_jButton_select_carActionPerformed

    private void jComboBox_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_cityActionPerformed
        // populate   Jcombobox address depending on the city
                populateComboboxAddress("pickup", jComboBox_city.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox_cityActionPerformed

    private void jComboBox_city2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_city2ActionPerformed
        // TODO add your handling code here:
        populateComboboxAddress("dropoff", jComboBox_city2.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox_city2ActionPerformed

    private void jButton_BookCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BookCarActionPerformed
        // add new booking 
        //get car info 
        try
        {
            int car_id  = Integer.parseInt(jLabel_car_id.getText());
        // get the customer info
        int customer_id = Integer.parseInt(jLabel_customer_id.getText());
        //get the pick info 
        String pickup_city = jComboBox_city.getSelectedItem().toString();
        String pickup_address = jComboBox_address.getSelectedItem().toString();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String pickup_date =dateFormat.format(jDateChooser_date.getDate());
        Date pickup_date_ = dateFormat.parse(pickup_date);
        String pickup_time = timePicker_time.getText();
        // get drop off info
        String dropoof_city = jComboBox_city2.getSelectedItem().toString();
        String dropoof_address = jComboBox_address2.getSelectedItem().toString();
        String dropoof_date =dateFormat.format(jDateChooser_date2.getDate());
        Date dropoff_date_ = dateFormat.parse(dropoof_date);
        String dropoff_time = timePicker_time2.getText();
        
        
        
        // to get data difference in days
        long diff = dropoff_date_.getTime() - pickup_date_.getTime();
        //System.out.println(diff);
        
        int diff_days = (int) (diff / 1000/60 /60/24);
        //System.out.println(diff_days);
        int price = Integer.valueOf( jLabel_car_price.getText());
        int total_price =  diff_days *price;
        
         jLabel_car_totalprice.setText(String.valueOf(total_price));
        
        if(dropoff_date_.before(pickup_date_))
        {
            JOptionPane.showMessageDialog(null, "The drop off date Must be After The Pickup Date","Invalid Info",2);
        }
        else if(dropoff_date_.equals(pickup_date_))
        {
            if (timePicker_time2.getTime().isBefore(timePicker_time.getTime()))
            {
                JOptionPane.showMessageDialog(null, "The drop off date Must be After The Pickup Date","Invalid Info",2);
            }
            else
            {
                 booking.addNewBooking(car_id, customer_id, pickup_city, pickup_address, pickup_date, pickup_time, dropoof_city, dropoof_address, dropoof_date, dropoff_time, car_id); 
            }
        }
        else
        {
            booking.addNewBooking(car_id, customer_id, pickup_city, pickup_address, pickup_date, pickup_time, dropoof_city, dropoof_address, dropoof_date, dropoff_time, car_id);
        }
        
        
            
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Enter Valid data [ "+ex+" ]","Invalid Info",2);
        }
        
    }//GEN-LAST:event_jButton_BookCarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     try{
         
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String pickup_date =dateFormat.format(jDateChooser_date.getDate());
        Date pickup_date_ = dateFormat.parse(pickup_date);
        // get drop off info

        String dropoof_date =dateFormat.format(jDateChooser_date2.getDate());
        Date dropoff_date_ = dateFormat.parse(dropoof_date);
              // to get data difference in days
        long diff = dropoff_date_.getTime() - pickup_date_.getTime();
        //System.out.println(diff);
        int diff_days = (int) (diff / 1000/60 /60/24);
        //System.out.println(diff_days);
        int price = Integer.valueOf( jLabel_car_price.getText());
        int total_price =  diff_days *price;
        
         jLabel_car_totalprice.setText(String.valueOf(total_price));
              }catch(Exception ex){
                  
              }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Form_BookCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Form_BookCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Form_BookCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Form_BookCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_BookCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_BookCar;
    private javax.swing.JButton jButton_Select_Cusstomer;
    private javax.swing.JButton jButton_select_car;
    private javax.swing.JComboBox<String> jComboBox_address;
    private javax.swing.JComboBox<String> jComboBox_address2;
    private javax.swing.JComboBox<String> jComboBox_brand;
    private javax.swing.JComboBox<String> jComboBox_city;
    private javax.swing.JComboBox<String> jComboBox_city2;
    private com.toedter.calendar.JDateChooser jDateChooser_date;
    private com.toedter.calendar.JDateChooser jDateChooser_date2;
    private javax.swing.JLabel jLabel_Tittle;
    private javax.swing.JLabel jLabel_address;
    private javax.swing.JLabel jLabel_address2;
    private javax.swing.JLabel jLabel_brand;
    private static javax.swing.JLabel jLabel_brand_id;
    private javax.swing.JLabel jLabel_car;
    private static javax.swing.JLabel jLabel_car_id;
    private static javax.swing.JLabel jLabel_car_model;
    private static javax.swing.JLabel jLabel_car_price;
    private static javax.swing.JLabel jLabel_car_totalprice;
    private javax.swing.JLabel jLabel_city;
    private javax.swing.JLabel jLabel_city2;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_customer;
    private static javax.swing.JLabel jLabel_customer_id;
    private javax.swing.JLabel jLabel_customer_id1;
    private javax.swing.JLabel jLabel_customer_id3;
    private javax.swing.JLabel jLabel_customer_id5;
    private javax.swing.JLabel jLabel_customer_id6;
    private javax.swing.JLabel jLabel_customer_price1;
    private javax.swing.JLabel jLabel_date;
    private javax.swing.JLabel jLabel_date2;
    private javax.swing.JLabel jLabel_drop_off;
    private javax.swing.JLabel jLabel_for_back;
    private javax.swing.JLabel jLabel_pick_up;
    private javax.swing.JLabel jLabel_select_a_car;
    private javax.swing.JLabel jLabel_select_customer;
    private javax.swing.JLabel jLabel_time;
    private javax.swing.JLabel jLabel_time2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_drop_off;
    private javax.swing.JPanel jPanel_pick_up;
    private javax.swing.JPanel jPanel_select_car;
    private javax.swing.JPanel jPanel_select_customer;
    private static javax.swing.JTextField jTextField_customer_name;
    private com.github.lgooddatepicker.components.TimePicker timePicker_time;
    private com.github.lgooddatepicker.components.TimePicker timePicker_time2;
    // End of variables declaration//GEN-END:variables
}
