package java_car_rental;

import java.awt.Color;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author yidnek
 */
public class Form_Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Form_Dashboard
     */
    
     Border white_border  = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
     Border empty_border  = BorderFactory.createMatteBorder(1, 1, 1, 1, new  Color( 0,102,102 ));
     
    public Form_Dashboard() {
        initComponents();
        
        // center form
        
        this.setLocationRelativeTo(null);
        
        // dispaly images
        
        dispalyimages(jLabel_cars_logo.getWidth(),jLabel_cars_logo.getHeight(),"images/ford-mustang.png",jLabel_cars_logo);
        dispalyimages(jLabel_customer_logo.getWidth(),jLabel_customer_logo.getHeight(),"images/man.png",jLabel_customer_logo);
        dispalyimages(jLabel_booked_logo.getWidth(),jLabel_booked_logo.getHeight(),"images/calendar.png",jLabel_booked_logo);
        
        
        // set borders 
        
        lbl_Brands.setBorder(empty_border);
        lbl_Cars.setBorder(empty_border);
        lbl_Location.setBorder(empty_border);
        lbl_booking.setBorder(empty_border);
        lbl_customer.setBorder(empty_border);
        lbl_users.setBorder(empty_border);
        
        
        
    }
    
    // craete function to resize the images so it can fit jlabel
    
    public void dispalyimages(int width, int height,String image_path,JLabel label)
    {
        // get the images
        
        ImageIcon imageIcon = new ImageIcon(getClass().getResource(image_path));
        // resize the image
        Image image = imageIcon.getImage().getScaledInstance(width, height,  Image.SCALE_SMOOTH);
        // set the image into the jlabel
        label.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbl_Brands = new javax.swing.JLabel();
        lbl_Location = new javax.swing.JLabel();
        lbl_Cars = new javax.swing.JLabel();
        lbl_customer = new javax.swing.JLabel();
        lbl_booking = new javax.swing.JLabel();
        lbl_users = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_cars_logo = new javax.swing.JLabel();
        jLabel_cars_count = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_booked_logo = new javax.swing.JLabel();
        jLabel_booked_count = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel_customer = new javax.swing.JLabel();
        jLabel_customer_logo = new javax.swing.JLabel();
        jLabel_customer_count = new javax.swing.JLabel();
        lbl_userprofile_pic = new javax.swing.JLabel();
        lbl_logged_username = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 600));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(1080, 600));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        lbl_Brands.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lbl_Brands.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Brands.setText("Brands");
        lbl_Brands.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Brands.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_BrandsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_BrandsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_BrandsMouseExited(evt);
            }
        });

        lbl_Location.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lbl_Location.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Location.setText("Location");
        lbl_Location.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Location.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_LocationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_LocationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_LocationMouseExited(evt);
            }
        });

        lbl_Cars.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lbl_Cars.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Cars.setText("Cars");
        lbl_Cars.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Cars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_CarsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_CarsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_CarsMouseExited(evt);
            }
        });

        lbl_customer.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lbl_customer.setForeground(new java.awt.Color(255, 255, 255));
        lbl_customer.setText("Customers");
        lbl_customer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_customerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_customerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_customerMouseExited(evt);
            }
        });

        lbl_booking.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lbl_booking.setForeground(new java.awt.Color(255, 255, 255));
        lbl_booking.setText("Book a Car");
        lbl_booking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_bookingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_bookingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_bookingMouseExited(evt);
            }
        });

        lbl_users.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lbl_users.setForeground(new java.awt.Color(255, 255, 255));
        lbl_users.setText("Users");
        lbl_users.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_usersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_usersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_usersMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_booking, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Location, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Cars, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Brands, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_users, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lbl_Brands, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Cars, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Location, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_booking, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_users, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(254, 150));

        jPanel5.setBackground(new java.awt.Color(255, 178, 41));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cars");

        jLabel_cars_logo.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel_cars_logo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_cars_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_cars_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_cars_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel_cars_count.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel_cars_count.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_cars_count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_cars_count.setText("100");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_cars_count, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_cars_count, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
        );

        jLabel_close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("x");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(125, 60, 155));
        jPanel10.setPreferredSize(new java.awt.Dimension(254, 150));

        jPanel11.setBackground(new java.awt.Color(155, 89, 182));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Booked");

        jLabel_booked_logo.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel_booked_logo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_booked_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_booked_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_booked_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel_booked_count.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel_booked_count.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_booked_count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_booked_count.setText("100");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 254, Short.MAX_VALUE)
            .addComponent(jLabel_booked_count, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_booked_count, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(65, 160, 10));
        jPanel12.setPreferredSize(new java.awt.Dimension(254, 150));
        jPanel12.setVerifyInputWhenFocusTarget(false);

        jPanel13.setBackground(new java.awt.Color(75, 192, 18));

        jLabel_customer.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel_customer.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_customer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_customer.setText("Customer");

        jLabel_customer_logo.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel_customer_logo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_customer_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel_customer, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_customer_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_customer_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel_customer_count.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel_customer_count.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_customer_count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_customer_count.setText("100");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_customer_count, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_customer_count, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
        );

        lbl_userprofile_pic.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        lbl_userprofile_pic.setForeground(new java.awt.Color(0, 0, 0));
        lbl_userprofile_pic.setIcon(new javax.swing.ImageIcon("C:\\Users\\fanos\\OneDrive\\Documents\\Java_Car_Rental\\src\\java_car_rental\\images\\p3_.png")); // NOI18N
        lbl_userprofile_pic.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        lbl_userprofile_pic.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lbl_logged_username.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        lbl_logged_username.setForeground(new java.awt.Color(0, 0, 0));
        lbl_logged_username.setText("username");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbl_userprofile_pic, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_logged_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(559, 559, 559)
                        .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_logged_username))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lbl_userprofile_pic, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 309, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        // TO close 
                        int confirm = JOptionPane.showConfirmDialog(null, "Are You Sure You Want to Exit", "Confirm",JOptionPane.YES_NO_OPTION);
                if(confirm==JOptionPane.YES_OPTION)
                {
                    System.exit(0);
                }
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void lbl_BrandsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BrandsMouseClicked
        // TODO add your handling code here:
        Form_Brands brands = new Form_Brands();
        brands.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_BrandsMouseClicked

    private void lbl_CarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CarsMouseClicked
                Form_Car cars = new Form_Car();
                 this.dispose();
                cars.setVisible(true);
               
    }//GEN-LAST:event_lbl_CarsMouseClicked

    private void lbl_LocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LocationMouseClicked
                Form_Location location = new Form_Location();
                location.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_lbl_LocationMouseClicked

    private void lbl_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_customerMouseClicked
        Form_Customers customers = new Form_Customers();
        customers.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_lbl_customerMouseClicked

    private void lbl_BrandsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BrandsMouseEntered
        // TODO add your handling code here:
        lbl_Brands.setBorder(white_border);
    }//GEN-LAST:event_lbl_BrandsMouseEntered

    private void lbl_BrandsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BrandsMouseExited
        // TODO add your handling code here:
        lbl_Brands.setBorder(empty_border);
    }//GEN-LAST:event_lbl_BrandsMouseExited

    private void lbl_CarsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CarsMouseEntered
        // TODO add your handling code here:
        lbl_Cars.setBorder(white_border);
    }//GEN-LAST:event_lbl_CarsMouseEntered

    private void lbl_CarsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CarsMouseExited
        // TODO add your handling code here:
        lbl_Cars.setBorder(empty_border);
    }//GEN-LAST:event_lbl_CarsMouseExited

    private void lbl_LocationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LocationMouseEntered
        // TODO add your handling code here:
        lbl_Location.setBorder(white_border);
    }//GEN-LAST:event_lbl_LocationMouseEntered

    private void lbl_LocationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LocationMouseExited
        // TODO add your handling code here:
        lbl_Location.setBorder(empty_border);
    }//GEN-LAST:event_lbl_LocationMouseExited

    private void lbl_customerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_customerMouseEntered
        // TODO add your handling code here:
        lbl_customer.setBorder(white_border);
    }//GEN-LAST:event_lbl_customerMouseEntered

    private void lbl_customerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_customerMouseExited
        // TODO add your handling code here:
        lbl_customer.setBorder(empty_border);
    }//GEN-LAST:event_lbl_customerMouseExited

    private void lbl_bookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_bookingMouseClicked
        // TODO add your handling code here:
        
        Form_BookCar booking = new Form_BookCar();
        booking.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_lbl_bookingMouseClicked

    private void lbl_bookingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_bookingMouseEntered
        // TODO add your handling code here:
        lbl_booking.setBorder(white_border);
    }//GEN-LAST:event_lbl_bookingMouseEntered

    private void lbl_bookingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_bookingMouseExited
        // TODO add your handling code here:
        lbl_booking.setBorder(empty_border);
    }//GEN-LAST:event_lbl_bookingMouseExited

    private void lbl_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_usersMouseClicked
        // TODO add your handling code here:
        Form_Users user = new Form_Users();
        user.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_usersMouseClicked

    private void lbl_usersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_usersMouseEntered
        // TODO add your handling code here:
        lbl_users.setBorder(white_border);
    }//GEN-LAST:event_lbl_usersMouseEntered

    private void lbl_usersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_usersMouseExited
        // TODO add your handling code here:
        lbl_users.setBorder(empty_border);
    }//GEN-LAST:event_lbl_usersMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_booked_count;
    private javax.swing.JLabel jLabel_booked_logo;
    private javax.swing.JLabel jLabel_cars_count;
    private javax.swing.JLabel jLabel_cars_logo;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_customer;
    private javax.swing.JLabel jLabel_customer_count;
    private javax.swing.JLabel jLabel_customer_logo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl_Brands;
    private javax.swing.JLabel lbl_Cars;
    private javax.swing.JLabel lbl_Location;
    private javax.swing.JLabel lbl_booking;
    private javax.swing.JLabel lbl_customer;
    public static javax.swing.JLabel lbl_logged_username;
    public static javax.swing.JLabel lbl_userprofile_pic;
    private javax.swing.JLabel lbl_users;
    // End of variables declaration//GEN-END:variables
}
