/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_car_rental;

import Classes.Car;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ydnek
 */
public class Form_CarList extends javax.swing.JFrame {

    /**
     * Creates new form Form_CarList
     */
    
    Car car = new Car();
    // the car id 
    int carid;
    // table of jlabels 
    JLabel [] labels = new JLabel [6] ;
    public Form_CarList() {
        initComponents();
        
                // center the form
        this.setLocationRelativeTo(null);
              // populate the table
         populateJtableWithCars();
         
         labels [0] = jLabel_CarImage_1;
         labels [1] = jLabel_CarImage_2;
         labels [2] = jLabel_CarImage_3;
         labels [3] = jLabel_CarImage_4;
         labels [4] = jLabel_CarImage_5;
         labels [5] = jLabel_CarImage_6;  
    }
    
           public void displayimages(int width, int height,String image_path,JLabel label)
    {// get the images
        
        ImageIcon imageIcon = new ImageIcon(image_path);
        // resize the image
        Image image = imageIcon.getImage().getScaledInstance(width, height,  Image.SCALE_SMOOTH);
        // set the image into the jlabel
        label.setIcon(new ImageIcon(image));
    }
    
            public void displayByteImage(int width, int height,byte[] image_byte,JLabel label)
    {
        // get the images
        
        ImageIcon imageIcon = new ImageIcon(image_byte);
        // resize the image
        Image image = imageIcon.getImage().getScaledInstance(width, height,  Image.SCALE_SMOOTH);
        // set the image into the jlabel
        label.setIcon(new ImageIcon(image));
    }  
                     // create a function to populate the Table 
        public void populateJtableWithCars(){
        
        //populate arraylist
            ArrayList<Car> cars_list = car.carsList();
        // jtabel columns
        String [] columnsName = {"Id","brand","model","fuel","color","class","passengers","gearbox","price","ait_condtion","air_bag","sunroof","heated_seat","nav_systen","bluetooth","electric_window","gps"};
        // jtable rows
        Object[][] rows = new Object[cars_list.size()][columnsName.length];
        
        for(int i = 0;i < cars_list.size();i++){
            
            rows[i][0] = cars_list.get(i).getId();
            rows[i][1] = cars_list.get(i).getBrand();
            rows[i][2] = cars_list.get(i).getModel();
            rows[i][3] = cars_list.get(i).getFuel();
            rows[i][4] = cars_list.get(i).getColor();
            rows[i][5] = cars_list.get(i).getClass();
            rows[i][6] = cars_list.get(i).getPassengers();
            rows[i][7] = cars_list.get(i).getGearbox();
            rows[i][8] = cars_list.get(i).getPrice();
            rows[i][9] = cars_list.get(i).getAir_condi();
            rows[i][10] = cars_list.get(i).getAirbag();
            rows[i][11] = cars_list.get(i).getSunroof();
            rows[i][12] = cars_list.get(i).getHeated_seat();
            rows[i][13] = cars_list.get(i).getNav_system();
            rows[i][14] = cars_list.get(i).getBluetooth();
            rows[i][15] = cars_list.get(i).getElec_window();
            rows[i][16] = cars_list.get(i).getGps();
            
        }
        
        DefaultTableModel model = new DefaultTableModel(rows,columnsName);
        
        Table_Cars.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbl_brands_logo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jLabel_for_back = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Cars = new javax.swing.JTable();
        lbl_image_path = new javax.swing.JLabel();
        jLabel_Car_Image = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_CarImage_1 = new javax.swing.JLabel();
        jLabel_CarImage_2 = new javax.swing.JLabel();
        jLabel_CarImage_3 = new javax.swing.JLabel();
        jLabel_CarImage_4 = new javax.swing.JLabel();
        jLabel_CarImage_5 = new javax.swing.JLabel();
        jLabel_CarImage_6 = new javax.swing.JLabel();
        jButton_ShowSlider_from_ = new javax.swing.JButton();

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("jLabel1");
        jLabel4.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 600));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 600));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setToolTipText("");

        jPanel3.setBackground(new java.awt.Color(64, 224, 153));

        lbl_brands_logo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        lbl_brands_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_brands_logo.setText("brands log");

        jLabel5.setBackground(new java.awt.Color(64, 73, 220));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("All Cars");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel_close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("x");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        jLabel_for_back.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel_for_back.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_for_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_for_back.setText("<");
        jLabel_for_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_for_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_for_backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel_for_back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(lbl_brands_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 471, Short.MAX_VALUE)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_for_back, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_brands_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );

        Table_Cars.setAutoCreateRowSorter(true);
        Table_Cars.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Table_Cars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Table_Cars.setToolTipText("");
        Table_Cars.setFocusTraversalPolicyProvider(true);
        Table_Cars.setGridColor(new java.awt.Color(0, 0, 0));
        Table_Cars.setInheritsPopupMenu(true);
        Table_Cars.setRowHeight(30);
        Table_Cars.setSelectionBackground(new java.awt.Color(102, 102, 255));
        Table_Cars.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        Table_Cars.setShowGrid(true);
        Table_Cars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_CarsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Cars);

        lbl_image_path.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel_Car_Image.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_Car_Image.setForeground(new java.awt.Color(102, 102, 102));
        jLabel_Car_Image.setOpaque(true);

        jLabel_CarImage_1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_CarImage_1.setOpaque(true);

        jLabel_CarImage_2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_CarImage_2.setOpaque(true);

        jLabel_CarImage_3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_CarImage_3.setOpaque(true);

        jLabel_CarImage_4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_CarImage_4.setOpaque(true);

        jLabel_CarImage_5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_CarImage_5.setOpaque(true);

        jLabel_CarImage_6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_CarImage_6.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_CarImage_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_CarImage_4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_CarImage_2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_CarImage_5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_CarImage_3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_CarImage_6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CarImage_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_CarImage_2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_CarImage_3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CarImage_4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_CarImage_5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_CarImage_6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton_ShowSlider_from_.setText("Images Slider");
        jButton_ShowSlider_from_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ShowSlider_from_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lbl_image_path, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Car_Image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton_ShowSlider_from_, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_Car_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_ShowSlider_from_, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_image_path)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        // close the form
        int confirm = JOptionPane.showConfirmDialog(null, "Are You Sure You Want to Exit", "Confirm",JOptionPane.YES_NO_OPTION);
        if(confirm==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_for_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_for_backMouseClicked
        // TODO add your handling code here:

        Form_Car dashboard = new Form_Car();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_for_backMouseClicked

    private void Table_CarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_CarsMouseClicked
        // get the selected car image

        jLabel_Car_Image.setIcon(null);
        
        for(int i = 0; i < labels.length; i++)
        {
            labels[i].setIcon(null);
        }
        
        // get the selected car image
        int index = Table_Cars.getSelectedRow();
        int id = Integer.valueOf(Table_Cars.getValueAt(index,0).toString()); // car id 
                
                carid = id;  // to use it in the image slider form 
             
                ArrayList<Car.CarImage> images = car.carImageList(id);
                  // dispaly the image on the Jlabels
                  if (images.size() > 0){
                      
                      displayByteImage(jLabel_Car_Image.getWidth(),jLabel_Car_Image.getHeight(),images.get(0).getCar_img(),jLabel_Car_Image);
                      for (int i = 0; i < labels.length; i++)
                      {
                           displayByteImage(labels[i].getWidth(),labels[i].getHeight(),images.get(i).getCar_img(),labels[i]);  
                      }
                  }
                  else 
                  {
                      JOptionPane.showMessageDialog(null, "This Car Has No Images ","No Images ",2);
                  }
    }//GEN-LAST:event_Table_CarsMouseClicked

    private void jButton_ShowSlider_from_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ShowSlider_from_ActionPerformed
        // show car image in a slider
        try 
        {
            Form_CarImages_Slider  slider = new Form_CarImages_Slider (carid);
            slider.setVisible(true);
//            this.dispose();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, "This Car Has No Images ","No Images ",2);
        }
        

    }//GEN-LAST:event_jButton_ShowSlider_from_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Form_CarList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Form_CarList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Form_CarList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Form_CarList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_CarList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Cars;
    private javax.swing.JButton jButton_ShowSlider_from_;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_CarImage_1;
    private javax.swing.JLabel jLabel_CarImage_2;
    private javax.swing.JLabel jLabel_CarImage_3;
    private javax.swing.JLabel jLabel_CarImage_4;
    private javax.swing.JLabel jLabel_CarImage_5;
    private javax.swing.JLabel jLabel_CarImage_6;
    private javax.swing.JLabel jLabel_Car_Image;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_for_back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_brands_logo;
    private javax.swing.JLabel lbl_image_path;
    // End of variables declaration//GEN-END:variables
}
