
package java_car_rental;

import Classes.Location;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fanos
 */
public class Form_Location extends javax.swing.JFrame {

    /**
     * Creates new form Form_Location
     */
    
    Classes.Location location = new Classes.Location(); 
    ArrayList<Location> location_list = location.locationList();
    int index = 0;
    public Form_Location() {
        initComponents();
        setLocationRelativeTo(null);
        populateTableWithLocation();
    }
    
    
        public void populateTableWithLocation(){
        
            // clear arraylist
            location_list.clear();
            // populate arraylist
            location_list  = location.locationList();
        
        // jtabel columns
        
        String [] columnsName = {"Id","City","Address"};        
        
        // jtable rows
        
        Object[][] rows = new Object[location_list.size()][columnsName.length];
        
        for(int i = 0;i < location_list.size();i++){
            
            rows[i][0] = location_list.get(i).getId();
            rows[i][1] = location_list.get(i).getCity();
            rows[i][2] = location_list.get(i).getAddress();
        }
        
        DefaultTableModel model = new DefaultTableModel(rows,columnsName);
        
        Table_Location.setModel(model);
        
    }
        
     // create a function to display location    
        public void dispalyLocation(){
        
        Classes.Location selected_location = location_list.get(index);
        jSpinner_location_Id.setValue(selected_location.getId());
        ComboBox_City.setSelectedItem(selected_location.getCity());
        TextArea_Address.setText(selected_location.getAddress());
    }
        
        // Function to check empty fields  
        public boolean verify(){
            
        String address = TextArea_Address.getText();
        if(!address.trim().equals(""))
        {
            return true;
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Enter a Valid Location Address","Invalid Info",2);
            return false;
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jLabel_for_back = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Location = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        int max = 10000;
        int min = 0;
        int step = 1;
        int i = 0;

        SpinnerModel spinner_model = new SpinnerNumberModel(i,min,max,step);
        jSpinner_location_Id = new javax.swing.JSpinner(spinner_model);
        Button_add = new javax.swing.JButton();
        Button_edit = new javax.swing.JButton();
        Button_remove = new javax.swing.JButton();
        Button_Previous = new javax.swing.JButton();
        Button_Next = new javax.swing.JButton();
        Button_Frist = new javax.swing.JButton();
        Button_Last = new javax.swing.JButton();
        lbl_image_path = new javax.swing.JLabel();
        Button_refresh = new javax.swing.JButton();
        Button_clear = new javax.swing.JButton();
        ComboBox_City = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextArea_Address = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 600));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 600));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setToolTipText("");

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        jLabel5.setBackground(new java.awt.Color(64, 73, 220));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Locations ");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel_close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("x");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        jLabel_for_back.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel_for_back.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_for_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_for_back.setText("<");
        jLabel_for_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_for_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_for_backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel_for_back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(376, 376, 376)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 352, Short.MAX_VALUE)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_for_back, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        Table_Location.setAutoCreateRowSorter(true);
        Table_Location.setBackground(new java.awt.Color(255, 255, 255));
        Table_Location.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0)));
        Table_Location.setForeground(new java.awt.Color(0, 0, 0));
        Table_Location.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Table_Location.setFocusTraversalPolicyProvider(true);
        Table_Location.setGridColor(new java.awt.Color(0, 0, 0));
        Table_Location.setInheritsPopupMenu(true);
        Table_Location.setSelectionBackground(new java.awt.Color(153, 153, 153));
        Table_Location.setSelectionForeground(new java.awt.Color(0, 0, 0));
        Table_Location.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_LocationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Location);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("City:");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Address:");

        jSpinner_location_Id.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        jSpinner_location_Id.setPreferredSize(new java.awt.Dimension(20, 32));

        Button_add.setBackground(new java.awt.Color(0, 51, 102));
        Button_add.setForeground(new java.awt.Color(255, 255, 255));
        Button_add.setText("Add");
        Button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_addActionPerformed(evt);
            }
        });

        Button_edit.setBackground(new java.awt.Color(0, 51, 102));
        Button_edit.setForeground(new java.awt.Color(255, 255, 255));
        Button_edit.setText("Edit");
        Button_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_editActionPerformed(evt);
            }
        });

        Button_remove.setBackground(new java.awt.Color(0, 51, 102));
        Button_remove.setForeground(new java.awt.Color(255, 255, 255));
        Button_remove.setText("Remove");
        Button_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_removeActionPerformed(evt);
            }
        });

        Button_Previous.setBackground(new java.awt.Color(0, 51, 102));
        Button_Previous.setForeground(new java.awt.Color(255, 255, 255));
        Button_Previous.setText(">");
        Button_Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PreviousActionPerformed(evt);
            }
        });

        Button_Next.setBackground(new java.awt.Color(0, 51, 102));
        Button_Next.setForeground(new java.awt.Color(255, 255, 255));
        Button_Next.setText("<");
        Button_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_NextActionPerformed(evt);
            }
        });

        Button_Frist.setBackground(new java.awt.Color(0, 51, 102));
        Button_Frist.setForeground(new java.awt.Color(255, 255, 255));
        Button_Frist.setText("<<");
        Button_Frist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_FristActionPerformed(evt);
            }
        });

        Button_Last.setBackground(new java.awt.Color(0, 51, 102));
        Button_Last.setForeground(new java.awt.Color(255, 255, 255));
        Button_Last.setText(">>");
        Button_Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LastActionPerformed(evt);
            }
        });

        lbl_image_path.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Button_refresh.setBackground(new java.awt.Color(0, 51, 102));
        Button_refresh.setForeground(new java.awt.Color(255, 255, 255));
        Button_refresh.setText("Refresh");
        Button_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_refreshActionPerformed(evt);
            }
        });

        Button_clear.setBackground(new java.awt.Color(0, 51, 102));
        Button_clear.setForeground(new java.awt.Color(255, 255, 255));
        Button_clear.setText("Clear");
        Button_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_clearActionPerformed(evt);
            }
        });

        ComboBox_City.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        ComboBox_City.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "City 1", "City 2", "City 3", "City 4" }));
        ComboBox_City.setToolTipText("");
        ComboBox_City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_CityActionPerformed(evt);
            }
        });

        TextArea_Address.setBackground(new java.awt.Color(255, 255, 255));
        TextArea_Address.setColumns(20);
        TextArea_Address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextArea_Address.setRows(5);
        jScrollPane3.setViewportView(TextArea_Address);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lbl_image_path, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Button_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Button_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Button_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Button_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox_City, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jSpinner_location_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3))))
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Button_Frist, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Button_Previous, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Button_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Button_Last, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner_location_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_City, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_image_path))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Frist)
                    .addComponent(Button_Previous)
                    .addComponent(Button_Last)
                    .addComponent(Button_add)
                    .addComponent(Button_edit)
                    .addComponent(Button_remove)
                    .addComponent(Button_Next))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_refresh)
                    .addComponent(Button_clear))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        // TO Close the Program 
                        int confirm = JOptionPane.showConfirmDialog(null, "Are You Sure You Want to Exit", "Confirm",JOptionPane.YES_NO_OPTION);
                if(confirm==JOptionPane.YES_OPTION)
                {
                    System.exit(0);
                }
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_for_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_for_backMouseClicked
        // TODO add your handling code here:

        Form_Dashboard dashboard = new Form_Dashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_for_backMouseClicked

    private void Table_LocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_LocationMouseClicked
        // get the selected brand
        int index = Table_Location.getSelectedRow();
        jSpinner_location_Id.setValue(Integer.valueOf(Table_Location.getValueAt(index, 0).toString()));
        ComboBox_City.setSelectedItem(Table_Location.getValueAt(index, 1).toString());
        TextArea_Address.setText(Table_Location.getValueAt(index, 2).toString());
    }//GEN-LAST:event_Table_LocationMouseClicked

    private void Button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_addActionPerformed
        // add new location
        String city = ComboBox_City.getSelectedItem().toString();
         String address =TextArea_Address.getText();
         
         if(verify())
         {
         location.addLocation(city, address);
         }
    }//GEN-LAST:event_Button_addActionPerformed

    private void Button_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_editActionPerformed
        // edit brand
        int id = (int) jSpinner_location_Id.getValue();
        String city = ComboBox_City.getSelectedItem().toString();
        String address =TextArea_Address.getText();
        
        if(verify())
        {
        location.editLocation(id, city, address);
        }
    }//GEN-LAST:event_Button_editActionPerformed

    private void Button_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_removeActionPerformed
        // remove Location

        try {
            int id =  (int)jSpinner_location_Id.getValue();
            int confirm = JOptionPane.showConfirmDialog(null, "Are You Sure You Want to Delete this Location", "Confirm", JOptionPane.YES_NO_OPTION);
            if(confirm == JOptionPane.YES_OPTION){
            Classes.Location locations  = new Classes.Location();
            locations.removeLocation(id);
            }

        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Form_Brands.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Button_removeActionPerformed
 
    private void Button_PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PreviousActionPerformed
        // Button_Previous
           index --;
        if(index <  0){
            index = 0;
        }
        dispalyLocation();
    }//GEN-LAST:event_Button_PreviousActionPerformed

    private void Button_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_NextActionPerformed
        // Button_Next
        index++;
        if(index > location_list.size()-1){
            index = location_list.size()-1;
        }
        dispalyLocation();
    }//GEN-LAST:event_Button_NextActionPerformed

    private void Button_FristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_FristActionPerformed
        // TButton_Frist
        index = 0;
        dispalyLocation();
      
    }//GEN-LAST:event_Button_FristActionPerformed

    private void Button_LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LastActionPerformed
        // Button_Last
         index = location_list.size()-1;
         dispalyLocation();
    }//GEN-LAST:event_Button_LastActionPerformed

    private void Button_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_refreshActionPerformed
        // To refresh the Table
        populateTableWithLocation();
    }//GEN-LAST:event_Button_refreshActionPerformed

    private void Button_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_clearActionPerformed
        // TO clear fields
        jSpinner_location_Id.setValue(0);
        ComboBox_City.setSelectedIndex(0);
        TextArea_Address.setText("");
        
    }//GEN-LAST:event_Button_clearActionPerformed

    private void ComboBox_CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_CityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_CityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Location().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Frist;
    private javax.swing.JButton Button_Last;
    private javax.swing.JButton Button_Next;
    private javax.swing.JButton Button_Previous;
    private javax.swing.JButton Button_add;
    private javax.swing.JButton Button_clear;
    private javax.swing.JButton Button_edit;
    private javax.swing.JButton Button_refresh;
    private javax.swing.JButton Button_remove;
    private javax.swing.JComboBox<String> ComboBox_City;
    private javax.swing.JTable Table_Location;
    private javax.swing.JTextArea TextArea_Address;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_for_back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner_location_Id;
    private javax.swing.JLabel lbl_image_path;
    // End of variables declaration//GEN-END:variables
}
