
package java_car_rental;

import Classes.Brand_Cls;
import Classes.Car;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Ydnek
 */
public class Form_Car extends javax.swing.JFrame {

    /**
     * Creates new form Form_Car
     */
    
    Car car = new Car();
    Brand_Cls brand = new Brand_Cls();
    HashMap<Integer, String > map = brand.brandHasMap();
    
    
    public Form_Car() {
        initComponents();
        setLocationRelativeTo(this);
        
        // add RadioButton to the same group  
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButton_Manual);
        bg.add(jRadioButton_Automatic);
        
        // populate combobox with brands
        populateComboboxBrands();
        
    }
    
    // function to populate the JCombobox_brands with brands
    // and to do that we will use hashmap
    public void populateComboboxBrands()
    { 
        for( String s : map.values())
        {
            jComboBox_brand.addItem(s);
        } 
    }
    
            // Function to check empty fields  
        public boolean verify(){
            
        String model = jTextField_Model1.getText();
//        String _class = jTextField_calss.getText();
        
        if(!model.trim().equals("") )
        {
            return true;
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Enter a Valid Model and Class","Invalid Info",2);
            return false;
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbl_brands_logo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jLabel_for_back = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Button_Brand_list = new javax.swing.JButton();
        lbl_image_path = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox_Features_Air_Con = new javax.swing.JCheckBox();
        jCheckBox_Features_Airbags = new javax.swing.JCheckBox();
        jCheckBox_Features_Sunroof = new javax.swing.JCheckBox();
        jCheckBox_Features_Heated = new javax.swing.JCheckBox();
        jCheckBox_Features_Navigation = new javax.swing.JCheckBox();
        jCheckBox_Bluetooth = new javax.swing.JCheckBox();
        jCheckBox_Features_ElectricWindows = new javax.swing.JCheckBox();
        jCheckBox_Features_GPS = new javax.swing.JCheckBox();
        jComboBox_color = new javax.swing.JComboBox<>();
        jComboBox_brand = new javax.swing.JComboBox<>();
        jComboBox_fuel = new javax.swing.JComboBox<>();
        int max = 10000;
        int min = 100;
        int step = 20;
        int i = 100 ;
        SpinnerModel spinner_model = new SpinnerNumberModel(i, min, max, step);
        jSpinner_price = new javax.swing.JSpinner(spinner_model);
        jTextField_Model1 = new javax.swing.JTextField();
        Button_Add_Car = new javax.swing.JButton();
        Button_Add_Car_Image = new javax.swing.JButton();
        jRadioButton_Automatic = new javax.swing.JRadioButton();
        jRadioButton_Manual = new javax.swing.JRadioButton();
        Button_Edit = new javax.swing.JButton();
        jLabel_brand_id = new javax.swing.JLabel();
        int max_2 = 5;
        int min_2 = 2;
        int step_2 = 1;
        int i_2 = 2;
        SpinnerModel spinner1_model = new SpinnerNumberModel(i_2,min_2,max_2,step_2);
        jSpinner_Passengers = new javax.swing.JSpinner(spinner1_model);
        Button_Reset = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Button_Remove = new javax.swing.JButton();
        Button_CarList = new javax.swing.JButton();
        int maxt = 1000;
        int mint = 1;
        int stept = 1;
        int j = 1 ;
        SpinnerModel spinner_modelt = new SpinnerNumberModel(j, mint, maxt, stept);
        jSpinner_Id = new javax.swing.JSpinner(spinner_modelt);
        Button_Search = new javax.swing.JButton();
        jComboBox_carClass = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 600));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setToolTipText("");
        jPanel2.setPreferredSize(new java.awt.Dimension(1068, 585));

        jPanel3.setBackground(new java.awt.Color(199, 65, 181));

        lbl_brands_logo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        lbl_brands_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_brands_logo.setText("brands log");

        jLabel5.setBackground(new java.awt.Color(102, 0, 102));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cars");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel_close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("x");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        jLabel_for_back.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel_for_back.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_for_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_for_back.setText("<");
        jLabel_for_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_for_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_for_backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel_for_back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(lbl_brands_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_for_back, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_brands_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Brands:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Model:");

        Button_Brand_list.setBackground(new java.awt.Color(102, 0, 102));
        Button_Brand_list.setForeground(new java.awt.Color(255, 255, 255));
        Button_Brand_list.setText("Brand List");
        Button_Brand_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Brand_listActionPerformed(evt);
            }
        });

        lbl_image_path.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Fuel:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Price/day:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Passengers:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Color:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Features");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Calss:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Gearbox:");

        jCheckBox_Features_Air_Con.setText("Air Conditioning");

        jCheckBox_Features_Airbags.setText("Airbags");

        jCheckBox_Features_Sunroof.setText("Sunroof");

        jCheckBox_Features_Heated.setText("Heated Seats");

        jCheckBox_Features_Navigation.setText("Navigation System");

        jCheckBox_Bluetooth.setText("Bluetooth");

        jCheckBox_Features_ElectricWindows.setText("Electric Windows");

        jCheckBox_Features_GPS.setText("GPS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_Features_Airbags, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Features_Air_Con, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_Features_Heated, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Features_Sunroof, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_Bluetooth, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Features_Navigation, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_Features_GPS, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Features_ElectricWindows, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBox_Features_ElectricWindows)
                        .addGap(26, 26, 26)
                        .addComponent(jCheckBox_Features_GPS))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jCheckBox_Features_Navigation)
                            .addGap(26, 26, 26)
                            .addComponent(jCheckBox_Bluetooth))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCheckBox_Features_Sunroof)
                                .addGap(26, 26, 26)
                                .addComponent(jCheckBox_Features_Heated))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCheckBox_Features_Air_Con)
                                .addGap(26, 26, 26)
                                .addComponent(jCheckBox_Features_Airbags)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jComboBox_color.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_color.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_color.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "White", "Black", "Red", "Yellow", "Green", "Blue", "Grey", "Brown", "Orange" }));
        jComboBox_color.setOpaque(true);
        jComboBox_color.setPreferredSize(new java.awt.Dimension(170, 25));

        jComboBox_brand.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_brand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_brand.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_brand.setOpaque(true);
        jComboBox_brand.setPreferredSize(new java.awt.Dimension(170, 25));
        jComboBox_brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_brandActionPerformed(evt);
            }
        });

        jComboBox_fuel.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_fuel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_fuel.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_fuel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gas", "Diesel" }));
        jComboBox_fuel.setOpaque(true);
        jComboBox_fuel.setPreferredSize(new java.awt.Dimension(170, 25));

        jSpinner_price.setPreferredSize(new java.awt.Dimension(100, 25));

        jTextField_Model1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Model1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Model1.setOpaque(true);
        jTextField_Model1.setPreferredSize(new java.awt.Dimension(170, 25));

        Button_Add_Car.setBackground(new java.awt.Color(102, 0, 102));
        Button_Add_Car.setForeground(new java.awt.Color(255, 255, 255));
        Button_Add_Car.setText("Add");
        Button_Add_Car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Add_CarActionPerformed(evt);
            }
        });

        Button_Add_Car_Image.setBackground(new java.awt.Color(102, 0, 102));
        Button_Add_Car_Image.setForeground(new java.awt.Color(255, 255, 255));
        Button_Add_Car_Image.setText("Add Car Image");
        Button_Add_Car_Image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Add_Car_ImageActionPerformed(evt);
            }
        });

        jRadioButton_Automatic.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton_Automatic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_Automatic.setText("Automatic");
        jRadioButton_Automatic.setPreferredSize(new java.awt.Dimension(100, 25));

        jRadioButton_Manual.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton_Manual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_Manual.setText("Manual");
        jRadioButton_Manual.setPreferredSize(new java.awt.Dimension(100, 25));

        Button_Edit.setBackground(new java.awt.Color(102, 0, 102));
        Button_Edit.setForeground(new java.awt.Color(255, 255, 255));
        Button_Edit.setText("Edit");
        Button_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EditActionPerformed(evt);
            }
        });

        jLabel_brand_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_brand_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_brand_id.setText("#");

        jSpinner_Passengers.setPreferredSize(new java.awt.Dimension(100, 25));

        Button_Reset.setBackground(new java.awt.Color(102, 0, 102));
        Button_Reset.setForeground(new java.awt.Color(255, 255, 255));
        Button_Reset.setText("Reset");
        Button_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ResetActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("ID");

        Button_Remove.setBackground(new java.awt.Color(102, 0, 102));
        Button_Remove.setForeground(new java.awt.Color(255, 255, 255));
        Button_Remove.setText("Remove");
        Button_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RemoveActionPerformed(evt);
            }
        });

        Button_CarList.setBackground(new java.awt.Color(102, 0, 102));
        Button_CarList.setForeground(new java.awt.Color(255, 255, 255));
        Button_CarList.setText("Car List");
        Button_CarList.setPreferredSize(new java.awt.Dimension(130, 30));
        Button_CarList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CarListActionPerformed(evt);
            }
        });

        jSpinner_Id.setPreferredSize(new java.awt.Dimension(100, 25));

        Button_Search.setBackground(new java.awt.Color(0, 51, 153));
        Button_Search.setForeground(new java.awt.Color(255, 255, 255));
        Button_Search.setText("Search");
        Button_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SearchActionPerformed(evt);
            }
        });

        jComboBox_carClass.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_carClass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_carClass.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_carClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A-segment", "B-segment", "C-segment", "D-segment", "SUV", "Sports Car" }));
        jComboBox_carClass.setOpaque(true);
        jComboBox_carClass.setPreferredSize(new java.awt.Dimension(170, 25));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lbl_image_path, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jComboBox_fuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jComboBox_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(jTextField_Model1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(jComboBox_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(194, 194, 194)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)
                                                .addComponent(jRadioButton_Automatic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(jRadioButton_Manual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(164, 164, 164)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)
                                                .addComponent(jSpinner_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel_brand_id, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(118, 118, 118)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(20, 20, 20))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jComboBox_carClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jSpinner_Passengers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jSpinner_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button_Search))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Button_Add_Car, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Button_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Button_Brand_list, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Button_Add_Car_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Button_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Button_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Button_CarList, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox_carClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jSpinner_Passengers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton_Automatic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jRadioButton_Manual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jSpinner_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinner_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button_Search))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jComboBox_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jTextField_Model1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jComboBox_fuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jComboBox_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel_brand_id, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lbl_image_path)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Button_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Button_Add_Car, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Brand_list, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Add_Car_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_CarList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(283, 283, 283))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        // to close the program  
                int confirm = JOptionPane.showConfirmDialog(null, "Are You Sure You Want to Exit", "Confirm",JOptionPane.YES_NO_OPTION);
                if(confirm==JOptionPane.YES_OPTION)
                {
                    System.exit(0);
                }
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_for_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_for_backMouseClicked
        // TODO add your handling code here:

        Form_Dashboard dashboard = new Form_Dashboard();
        dashboard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel_for_backMouseClicked

    private void Button_Brand_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Brand_listActionPerformed
        // add new location
        Form_BrandList allbrand = new Form_BrandList();
        allbrand.setVisible(true);
         this.setVisible(false);
         this.setVisible(false);
      
    }//GEN-LAST:event_Button_Brand_listActionPerformed

    private void Button_Add_CarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Add_CarActionPerformed
        // add new car
        //car info 
        int brand = Integer.valueOf(jLabel_brand_id.getText());
        String model = jTextField_Model1.getText();
        String fuel = jComboBox_fuel.getSelectedItem().toString();
        String color = jComboBox_color.getSelectedItem().toString();
        String _class_ = jComboBox_carClass.getSelectedItem().toString();
        int passengers = (int)jSpinner_Passengers.getValue();
        String gearbox = "automatic";
        int  price = (int)jSpinner_price.getValue();
        
        // car features
        String air_condi = "no";
        String airbags = "no";
        String sunroof = "no";
        String heated_seates = "no";
        String nav_system = "no";
        String bluetooth = "no";
        String elec_win = "no";
        String gps = "no";
        
        if(jRadioButton_Manual.isSelected()){  gearbox = "manuel";  }
        
        if(jCheckBox_Features_Air_Con.isSelected()){  air_condi = "yes";  }
        if(jCheckBox_Features_Airbags.isSelected()){  airbags = "yes";  }
        if(jCheckBox_Features_Sunroof.isSelected()){  sunroof = "yes";  }
        if(jCheckBox_Features_Heated.isSelected()){  heated_seates = "yes";  }
        if(jCheckBox_Features_Navigation.isSelected()){  nav_system = "yes";  }
        if(jCheckBox_Bluetooth.isSelected()){  bluetooth = "yes";  }
        if(jCheckBox_Features_ElectricWindows.isSelected()){  elec_win = "yes";  }
        if(jCheckBox_Features_GPS.isSelected()){  gps = "yes";  }
        
        if(verify()){
            car.addCar( brand, model, fuel, color, _class_, passengers, gearbox, price, 
                air_condi, airbags, sunroof, heated_seates, nav_system, bluetooth, elec_win, gps);
        }
        
    }//GEN-LAST:event_Button_Add_CarActionPerformed

    private void Button_Add_Car_ImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Add_Car_ImageActionPerformed
        // Button To open  Car image  form 
        
        Form_CarImages carImages = new Form_CarImages();
        carImages.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_Add_Car_ImageActionPerformed

    private void Button_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EditActionPerformed
// Edit Car Info

        int brand = Integer.valueOf(jLabel_brand_id.getText());
        int id = Integer.valueOf( (int) jSpinner_Id.getValue() );
         
        String model = jTextField_Model1.getText();
        String fuel = jComboBox_fuel.getSelectedItem().toString();
        String color = jComboBox_color.getSelectedItem().toString();
        String _class_ =  jComboBox_carClass.getSelectedItem().toString();
        int passengers = (int)jSpinner_Passengers.getValue();
        String gearbox = "automatic";
        int  price = (int)jSpinner_price.getValue();
        
        // car features
        String air_condi = "no";
        String airbags = "no";
        String sunroof = "no";
        String heated_seates = "no";
        String nav_system = "no";
        String bluetooth = "no";
        String elec_win = "no";
        String gps = "no";
        
        if(jRadioButton_Manual.isSelected()){  gearbox = "manuel";  }
        
        if(jCheckBox_Features_Air_Con.isSelected()){  air_condi = "yes";  }
        if(jCheckBox_Features_Airbags.isSelected()){  airbags = "yes";  }
        if(jCheckBox_Features_Sunroof.isSelected()){  sunroof = "yes";  }
        if(jCheckBox_Features_Heated.isSelected()){  heated_seates = "yes";  }
        if(jCheckBox_Features_Navigation.isSelected()){  nav_system = "yes";  }
        if(jCheckBox_Bluetooth.isSelected()){  bluetooth = "yes";  }
        if(jCheckBox_Features_ElectricWindows.isSelected()){  elec_win = "yes";  }
        if(jCheckBox_Features_GPS.isSelected()){  gps = "yes";  }
        
        if(verify()){
            car.editCar(id,brand, model, fuel, color, _class_, passengers, gearbox, price, 
                air_condi, airbags, sunroof, heated_seates, nav_system, bluetooth, elec_win, gps);
        }
    }//GEN-LAST:event_Button_EditActionPerformed

    private void jComboBox_brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_brandActionPerformed
        // Get the selected brand id
        int brand_id = 0;
        for(Map.Entry<Integer, String > entry : map.entrySet())
        {
            if(entry.getValue().equals(jComboBox_brand.getSelectedItem().toString()))
            {
                brand_id = entry.getKey();
            }
         }
        jLabel_brand_id.setText(String.valueOf(brand_id));
    }//GEN-LAST:event_jComboBox_brandActionPerformed

    private void Button_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ResetActionPerformed
        //      Button to Reset all fields to there default value

        jTextField_Model1.setText("");
         jSpinner_price.setValue(100);
         //jTextField_calss.setText("");
         jLabel_brand_id.setText("");
         
         jSpinner_Passengers.setValue(2);
         jComboBox_fuel.setSelectedIndex(0);
         jComboBox_carClass.setSelectedIndex(0);
         jComboBox_color.setSelectedIndex(0);
         jComboBox_brand.setSelectedIndex(0);
         jRadioButton_Automatic.setSelected(true);
         
         jCheckBox_Bluetooth.setSelected(false);
         jCheckBox_Features_Air_Con.setSelected(false);
         jCheckBox_Features_Airbags.setSelected(false);
         jCheckBox_Features_ElectricWindows.setSelected(false);
         jCheckBox_Features_GPS.setSelected(false);
         jCheckBox_Features_Heated.setSelected(false);
         jCheckBox_Features_Navigation.setSelected(false);
         jCheckBox_Features_Sunroof.setSelected(false);
    }//GEN-LAST:event_Button_ResetActionPerformed

    private void Button_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RemoveActionPerformed
        // Remov Car
                try {
                    int id = Integer.valueOf( (int) jSpinner_Id.getValue() );
                    int confirm = JOptionPane.showConfirmDialog(null, "Are You Sure You Want to Delete this Car", "Confirm",JOptionPane.YES_NO_OPTION);
                    if(confirm==JOptionPane.YES_OPTION)
                    {
                        car.removeCar(id);
                    }
                } catch (Exception ex) {
                    java.util.logging.Logger.getLogger(Form_Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_Button_RemoveActionPerformed

    private void Button_CarListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CarListActionPerformed
        // Display Car Lists From
        
            Form_CarList carList = new Form_CarList();
            carList.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_Button_CarListActionPerformed

    private void Button_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SearchActionPerformed
        // Search car by id 
        int car_id =  (int) jSpinner_Id.getValue();
        Car new_car = car.getCarById(car_id);
        
        // reset all fields 
        Button_ResetActionPerformed(null);
        
        if(new_car != null)
        {
  
            jTextField_Model1.setText(new_car.getModel()); 
            jSpinner_Passengers.setValue(new_car.getPassengers());
           jSpinner_price.setValue(new_car.getPrice());
             
            jLabel_brand_id.setText((String.valueOf(new_car.getBrand()) ));
            jComboBox_brand.setSelectedItem(map.get(new_car.getBrand()));
            jComboBox_fuel.setSelectedItem(new_car.getFuel());
            jComboBox_carClass.setSelectedItem(new_car.getCalss_());
            jComboBox_color.setSelectedItem(new_car.getColor());
            
            if(new_car.getGearbox().equals("manuel"))  { jRadioButton_Manual.setSelected(true);  }
            
            if (new_car.getAirbag().equals("yes")) {jCheckBox_Features_Airbags.setSelected(true); }
            if(new_car.getAir_condi().equals("yes")) {  jCheckBox_Features_Airbags.setSelected(true);}
            if(new_car.getBluetooth().equals("yes")) {  jCheckBox_Bluetooth.setSelected(true);}
            if(new_car.getElec_window().equals("yes")) { jCheckBox_Features_ElectricWindows .setSelected(true);}
            if(new_car.getGps().equals("yes")) { jCheckBox_Features_GPS .setSelected(true);}
            if(new_car.getHeated_seat().equals("yes")) { jCheckBox_Features_Heated .setSelected(true);}
            if(new_car.getNav_system().equals("yes")) {  jCheckBox_Features_Navigation.setSelected(true);}
            if(new_car.getSunroof().equals("yes")) {  jCheckBox_Features_Sunroof.setSelected(true);}

            
        } 
    }//GEN-LAST:event_Button_SearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Form_Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Form_Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Form_Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Form_Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Car().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Add_Car;
    private javax.swing.JButton Button_Add_Car_Image;
    private javax.swing.JButton Button_Brand_list;
    private javax.swing.JButton Button_CarList;
    private javax.swing.JButton Button_Edit;
    private javax.swing.JButton Button_Remove;
    private javax.swing.JButton Button_Reset;
    private javax.swing.JButton Button_Search;
    private javax.swing.JCheckBox jCheckBox_Bluetooth;
    private javax.swing.JCheckBox jCheckBox_Features_Air_Con;
    private javax.swing.JCheckBox jCheckBox_Features_Airbags;
    private javax.swing.JCheckBox jCheckBox_Features_ElectricWindows;
    private javax.swing.JCheckBox jCheckBox_Features_GPS;
    private javax.swing.JCheckBox jCheckBox_Features_Heated;
    private javax.swing.JCheckBox jCheckBox_Features_Navigation;
    private javax.swing.JCheckBox jCheckBox_Features_Sunroof;
    private javax.swing.JComboBox<String> jComboBox_brand;
    private javax.swing.JComboBox<String> jComboBox_carClass;
    private javax.swing.JComboBox<String> jComboBox_color;
    private javax.swing.JComboBox<String> jComboBox_fuel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_brand_id;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_for_back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton_Automatic;
    private javax.swing.JRadioButton jRadioButton_Manual;
    private javax.swing.JSpinner jSpinner_Id;
    private javax.swing.JSpinner jSpinner_Passengers;
    private javax.swing.JSpinner jSpinner_price;
    private javax.swing.JTextField jTextField_Model1;
    private javax.swing.JLabel lbl_brands_logo;
    private javax.swing.JLabel lbl_image_path;
    // End of variables declaration//GEN-END:variables
}
